version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: pg_logical_replication
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword!@#%1234
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=5"
      - "-c"
      - "max_wal_senders=5"
    restart: unless-stopped

  target_postgres:
    image: postgres:14
    container_name: pg_target
    environment:
      POSTGRES_USER: targetuser
      POSTGRES_PASSWORD: targetpassword!@#1234
      POSTGRES_DB: targetdb
    volumes:
      - target_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

  nats:
    image: nats:latest
    container_name: pg_flo_nats
    command: ["-c", "/etc/nats/nats-server.conf"]
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf
      - nats_data:/data
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped

volumes:
  postgres_data:
  target_postgres_data:
  nats_data:
